.PHONY: clean All

All:
	@echo "----------Building project:[ ClientProj - Debug ]----------"
	@"$(MAKE)" -f  "ClientProj.mk"
clean:
	@echo "----------Cleaning project:[ ClientProj - Debug ]----------"
	@"$(MAKE)" -f  "ClientProj.mk" clean
