.PHONY: clean All

All:
	@echo "----------Building project:[ Factorial - Debug ]----------"
	@cd "factorial" && "$(MAKE)" -f  "Factorial.mk"
clean:
	@echo "----------Cleaning project:[ Factorial - Debug ]----------"
	@cd "factorial" && "$(MAKE)" -f  "Factorial.mk" clean
