.PHONY: clean All

All:
	@echo "----------Building project:[ ClientProj - Debug ]----------"
	@cd "text-query-system" && "$(MAKE)" -f  "ClientProj.mk"
clean:
	@echo "----------Cleaning project:[ ClientProj - Debug ]----------"
	@cd "text-query-system" && "$(MAKE)" -f  "ClientProj.mk" clean
