.PHONY: clean All

All:
	@echo "----------Building project:[ TestProj - Debug ]----------"
	@cd "text-query-system" && "$(MAKE)" -f  "TestProj.mk"
clean:
	@echo "----------Cleaning project:[ TestProj - Debug ]----------"
	@cd "text-query-system" && "$(MAKE)" -f  "TestProj.mk" clean
